// D3WEBGPU Phase 2 — boot the MODULARIZE Emscripten engine from React.
//
// The Emscripten build emits d3wasm.js (a `DoomModule` async factory) + d3wasm.wasm.
// The demo data preloader is a SEPARATE classic script, demo00.js, generated by
// file_packager.py. It begins with `var Module = typeof Module != 'undefined' ?
// Module : {}` and (because FS isn't ready at load time) pushes runWithFS onto
// Module.preRun; runWithFS later fetches demo00.data and gates main() with a run
// dependency. Under MODULARIZE there is no global Module, so demo00.js must
// augment the SAME object passed to DoomModule(). The orchestration:
//
//   1. build a config object (canvas, locateFile, print, setStatus, preRun, ...)
//   2. window.Module = config          (so demo00.js's top-level `var Module`
//                                       picks up `config` and augments it)
//   3. load demo00.js (classic <script>) -> augments window.Module (= config):
//                                       pushes runWithFS to config.preRun
//   4. load d3wasm.js  (classic <script>) -> defines window.DoomModule
//   5. DoomModule(window.Module) -> Promise<Module>; set window.Module = M
//
// `var Module=moduleArg` in the factory means config === M after boot, so the
// _d3_* KEEPALIVE exports land on the very object React holds a ref to. The
// setupD3memfs preRun callback (FS paths + IDBFS mount) is pushed by the engine's
// own --pre-js (pre.js); we only seed config.preRun = [].
//
// Verified equivalent: build-wasm/d3wasm-modtest.html (Phase 2 Stage A).

const CACHE_VERSION = 'v2';

function loadScript(src) {
  return new Promise((resolve, reject) => {
    const s = document.createElement('script');
    s.src = src;
    s.async = false; // preserve insertion order; onload still resolves after execution
    s.onload = () => resolve();
    s.onerror = () => reject(new Error('Failed to load script: ' + src));
    document.head.appendChild(s);
  });
}

/**
 * Boot the engine into `canvas`. Returns a Promise<Module> (the engine instance,
 * with the _d3_* KEEPALIVE exports). `hooks` optional: { setStatus }.
 */
export function bootDoom(canvas, hooks = {}) {
  const setStatus = hooks.setStatus || ((t) => console.log('[d3]', t));

  const config = {
    canvas,
    preRun: [],
    postRun: [],
    // Cache-bust engine files (belt-and-suspenders with the dev server's no-store).
    locateFile: (p) =>
      p.endsWith('.wasm') || p.endsWith('.data') || p.endsWith('.js')
        ? p + '?v=' + CACHE_VERSION
        : p,
    print: function (t) {
      if (arguments.length > 1) t = Array.prototype.slice.call(arguments).join(' ');
      console.log(t);
    },
    printErr: function (t) {
      if (arguments.length > 1) t = Array.prototype.slice.call(arguments).join(' ');
      console.error(t);
    },
    setStatus,
    totalDependencies: 0,
    monitorRunDependencies: function (left) {
      config.totalDependencies = Math.max(config.totalDependencies, left);
      const msg = left
        ? 'Preparing... (' + (config.totalDependencies - left) + '/' + config.totalDependencies + ')'
        : 'All downloads complete.';
      config.setStatus(msg);
    },
  };

  // Guard against a lost WebGL context (migrated from shell.html).
  canvas.addEventListener('webglcontextlost', (e) => {
    alert('WebGL context lost. You will need to reload the page.');
    e.preventDefault();
  }, false);

  // Step 2: expose the config as the global Module so demo00.js augments it.
  window.Module = config;

  // Steps 3-5: load the preloader, then the engine, then boot the factory.
  return loadScript('demo00.js')
    .then(() => loadScript('d3wasm.js'))
    .then(() => {
      if (typeof window.DoomModule !== 'function') {
        throw new Error('DoomModule factory not defined after loading d3wasm.js');
      }
      // DoomModule(config) returns a Promise<Module> (the factory is async).
      return Promise.resolve(window.DoomModule(window.Module));
    })
    .then((M) => {
      if (!M) throw new Error('DoomModule resolved with no Module instance');
      window.Module = M; // engine instance (=== config); carries _d3_* exports
      return M;
    });
}